version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: supertokens_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  supertokens:
    image: supertokens/supertokens-core:latest
    container_name: supertokens
    restart: unless-stopped
    environment:
      - SUPERTOKENS_DATABASE_URL=postgresql://admin:admin123@postgres:5432/supertokens_db
      - SUPERTOKENS_APP_NAME=VigilioServices
      - SUPERTOKENS_API_DOMAIN=http://localhost:3000
      - SUPERTOKENS_WEBSITE_DOMAIN=http://localhost:5173
    ports:
      - "3567:3567"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      PORT: 3000
      SUPERTOKENS_CONNECTION_URI: http://supertokens:3567
    ports:
      - "3000:3000"
    depends_on:
      - supertokens
      - postgres
